### ISSUE TITLE
es6 syntax

### ISSUE THREAD

**Issue by gor181** [Linesmerrill/atom-mocha-snippets#1]
Nice work on the plugin, really helpful! 

This is more a question and a feature request then an issue.
Is there a possibility to use arrow functions?

So we get:

```
it('component', () => {
    expect(wrapper).to.be.a('object');
});
```

instead of:

```
it('component', function () {
    expect(wrapper).to.be.a('object');
});
```

Cheeers

**Comment by Linesmerrill** [comment]
Hi @gor181  sorry for the super long reply to your question. First off I just wanted to thank you for using this package and I am glad you are enjoying it!

I love the es6 improvement but unfortunately the project I am currently working on was originally written pre es6. Due to this, it currently has everything using the explicit "function" syntax. This was one of the main reasons I created this package, to help simplify having to type it every single time.

What would be great is if there was a way to have a settings option that would allow the user to toggle es6 syntax on or off. I really have no idea how to do that, but if you wanted to take a stab at that and submit a pull request I would gladly merge that into this package. Thanks for your time and I hope you continue to use this!

**Comment by gor181** [comment]
heya @Linesmerrill ,

Yes the toggle would definitely make sense. I'll try to look into it.

Cheers,
Goran

**Comment by coichedid** [comment]
Hi @Linesmerrill and @gor181 ,

I'm looking around some solution for this toggle that can style snippets into ES5 or ES6 and I can't find nothing.
I have an idea.
What about have snippets postfixed with 5 for ES5 and default - without postfix, for ES6, or vice versa?
Something like:
'mocha describe':
    'prefix': 'describe'
    'body': 'describe("$1", () => {\n\t$2\n});\n$3'
and
'mocha describe5':
    'prefix': 'describe5'
    'body': 'describe("$1", function(){\n\t$2\n});\n$3'

What do you all think about it?
I can fork and do those changes.

Cheers,
Coi

**Comment by coichedid** [comment]
Hello, it's me again!

I started to do those changes on a forked project and I found that these snippets aren't working on my Atom.
After some investigations, I found that my JS files are detected as Babel language because I have language-babel (https://github.com/gandm/language-babel) installed.
With this case, it is much easier to do atom-mocha-snippets to work with ES6. We just need to create another CSON file under snippets folder and source it to babel language like this:
'.source.js.jsx':
  'mocha describe':
    'prefix': 'describe'
    'body': 'describe("$1", () => {\n\t$2\n});\n$3'
...

The first line tells that those snippets only work with scope "source.js.jsx", the same defined by language-babel. Got it?! No settings, no snippet duplication, just scope definitions.

I will add this file to my forked project and make a PR to @Linesmerrill project.

Cheers,
Coi

**Comment by MitchLillie** [comment]
I know I'm late to the party here, but wasn't this change a bit much? A couple of reasons:

* The [official Mocha docs](https://mochajs.org/#arrow-functions) recommend not using arrow functions
* Using the snippets, I can very easily create a test that will always throw a `TypeError`:

```
describe('', () => {
	it('', () => {
		this.timeout(100000);
		expect(true).to.be.true
	});
});
```

I guess I'm confused how arrow functions benefit atom-mocha-snippets or Mocha in general with the exception of not reading the word `function` a thousand times.
 

---

Edit:

For context, I am running Mocha without Babel in Node 8 or 9. But the "language-babel" package is still the only one that features syntax highlighting for ES6/7 features. atom-mocha-snippets checks my language, sees that it is Babel, and uses these darn arrows everywhere.
